### ISSUE TITLE
Document dependency on Python2/Incompatibility with Python3

### ISSUE THREAD

**Issue by jshoyer** [fmenardo/Treemmer#1]
If I am reading correctly, the Treemmer.py script cannot be used with Python3, because it uses Python2-style parenthesis-free print statements.
If I try to run it with Python3 if fails at [line 55](https://github.com/fmenardo/Treemmer/blob/1c4dedef3070541f28b2f29c805b89e8bec3a54b/Treemmer.py#L55).

You might consider modifying Treemmer.py so that it can be used with Python3, given that Python2 support will end.
(I did not investigate any compatibility issues beyond the print statements.)

**Comment by fmenardo** [comment]
Yes, that's a good suggestion,

It is not only the print statements, there are other part that are not python3 compatible.
I'll work on  a new release compatible with python 2 and 3

**Comment by fmenardo** [comment]
From version 0.3 Treemmer is compatible with both python 2 and python 3
