### ISSUE TITLE
Examples broken with v0.3

### ISSUE THREAD

**Issue by matthieu-haudiquet** [fmenardo/Treemmer#2]
Hello, 
i can't seem to be able to run Treemmer_v0.3.py (even though Treemmer.py works fine 👍  )

Here's a reproducible example:

` python3 Treemmer_v0.3.py -lm examples/pruning_options_tutorial/MTB_meta_info_lineages -mc 250 examples/pruning_options_tutorial/MTB_tree_trimmed_tree_RTL_0.95 `

```
Traceback (most recent call last):
  File "Treemmer-master/Treemmer_v0.3.py", line 452, in <module>
    dict_meta = read_list_meta(arguments.list_meta)
  File "Treemmer-master/Treemmer_v0.3.py", line 339, in read_list_meta
    list_meta = list(reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

EDIT: see my pull request for a quick fix ( I hope)

Best, 
Matthieu

**Comment by fmenardo** [comment]
Hi, thanks!

apparently -lm and -lmc options were not really compatible with python3 (they were working with python2), I pushed an update that fixed this + another small thing. Now they should work with both versions
