### ISSUE TITLE
AttributeError while pruning a SCoV2 tree

### ISSUE THREAD

**Issue by Koen-vdl** [fmenardo/Treemmer#4]
I wanted to give treemmer a try today to prune the daily global SCoV2 tree from nextstrain to a more manageable size but I encountered an error.

` python3 Treemmer_v0.3.py ../nextstrain.nwk --cpu 10`

Treemmer gets to iteration 167 and dies. 

```
RTL :   0.9995278628049258 N_seq:       3811

iter            167
Traceback (most recent call last):
  File "Treemmer_v0.3.py", line 577, in <module>
    t = prune_t(leaf_to_p,t)                            #do the tree pruning
  File "Treemmer_v0.3.py", line 268, in prune_t
    if (len(parent.get_children()) == 2):
AttributeError: 'NoneType' object has no attribute 'get_children' 

```
I uploaded the nwk file here in case it would help:
https://e.pcloud.link/publink/show?code=XZCcvkZLJ09L94PUC8Khoht2N0Njp63EVoX

**Comment by fmenardo** [comment]
Hi @Koen-vdl,

the nextstrain tree has a strange format, some tips have a "double branch length" (e.g.  (NewZealand/20VR0174/2020:0):0.004043652658310748

I think this is a mistake in nextstrain's trees, but let me know if I'm missing something

I attach a sanitized version of the tree on which treemmer works.

Please download the last version of Treemmer, I just pushed a fix to deal with cases in which the root is a polytomy

[nextstrain_sanitized.txt](https://github.com/fmenardo/Treemmer/files/6164474/nextstrain_sanitized.txt)
