### ISSUE TITLE
Python script is not working even with the tutorial files

### ISSUE THREAD

**Issue by maalkhamis** [fmenardo/Treemmer#5]
Dear Authors, 

I'm trying to use your program to reduce the size of my sequence collection: I've install the dependencies and all versions of python, but when I run the basic tutorial command I got this error message:
(base) malkhamis@Mohammads-iPro Treemmer-master % python Treemmer_v0.3.py -lm MTB_meta_info_lineages -mc 250 MTB_tree_trimmed_tree_RTL_0.95
Traceback (most recent call last):
  File "Treemmer_v0.3.py", line 443, in <module>
    t = Tree(arguments.INFILE,format=1)
  File "/Users/malkhamis/opt/anaconda3/lib/python3.8/site-packages/ete3/coretype/tree.py", line 212, in __init__
    read_newick(newick, root_node = self, format=format,
  File "/Users/malkhamis/opt/anaconda3/lib/python3.8/site-packages/ete3/parser/newick.py", line 264, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete3.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.
(base) malkhamis@Mohammads-iPro Treemmer-master % 

I would appreciate your help in this.
Cheers!
Moh

**Comment by fmenardo** [comment]
Dear @maalkhamis 
The example works for me, your error message suggests that your input file is not where you think it is (check the path) or is corrupted. From what you posted it seems you running Treemmer from the Treemmer-master folder, while the files are in the examples/pruning_options_tutorial folder.

I hope this helps

Best wishes

Fabrizio
