### ISSUE TITLE
Python 3 version crashes where Python 2 version works

### ISSUE THREAD

**Issue by bede** [fmenardo/Treemmer#6]
Hi there,
Thanks for developing this software. I notice that the Python 3 version crashes, when the exact same command given to the Python 2 script works. Environments were created using `conda create -n treemmer2 python=2 ete3 joblib numpy matplotlib` and `conda create -n treemmer3 python=3 ete3 joblib numpy matplotlib`

The following command errors:
```
(treemmer3) ameerega:2021-04-28 bede$ python Treemmer/Treemmer_v0.3.py -X 100 t_clean.nwk 
usage: Treemmer_v0.3.py [-h] [-X [X ...]] [-RTL [0-1 ...]] [-r [INT]] [-p] [-pr] [-lp [0,1,2]] [-np] [-fp] [-c [INT]] [-lm [path/to/file]] [-mc [INT]] [-lmc [path/to/file]]
                        [-v [0,1,2]] [-sc1 [leaf_name]] [-sc2 [leaf_name]] [-sa] [-pa] [-pc] [-sX [sX]] [-sRTL [0-1]]
                        INFILE
Treemmer_v0.3.py: error: argument -X/--stop_at_X_leaves: invalid int value: 't_clean.nwk'
```

In contrast, the following command in a Python 2 env appears to run successfully:
```
(treemmer2) ameerega:2021-04-28 bede$ python Treemmer/Treemmer.py -X 100 t_clean.nwk
```

My second question is what is the correct format for passing multiple X values? The syntax suggested in the command line help does not appear to be accepted – it expects an integer which would preclude passing multiple integers.

Thank you,
Bede

**Comment by fmenardo** [comment]
Hi @bede ,
in the last version of Treemmer the path to the newick tree must be the first argument: python Treemmer_v0.3.py INFILE [options], I updated the suggested usage in the help

this has nothing to do with the python versions, Treemmer.py is the first version of Treemmer, in that one the position of the INFILE did not matter, but I highly reccomend to use the last version.

Let me know if you have further issues

**Comment by fmenardo** [comment]
Hi @bede,

I forgot one piece of the answer: you can pass multiple -X and .RTL values by calling the option(s) several times eg:

`python Treemmer_v0.3.py input_file -X 10 -X 90 -RTL 0.95 -RTL 0.5` 

I hope this helps

**Comment by bede** [comment]
Thank you @fmenardo for fixing and clarifying the syntax. I'll give this a try later

**Comment by bede** [comment]
Hi again: I have found that the following command only produces a single output file for `-X 500` with the latest version uploaded two days ago. All values of -X except the last are ignored.

```
$ python Treemmer/Treemmer_v0.3.py t_clean.nwk -X 20 -X 50 -X 100 -X 200 -X 500
```

Otherwise the latest version is now working as expected, thank you.

**Comment by fmenardo** [comment]
Hi @bede,

yes, sorry, the correct syntax is 
` python Treemmer/Treemmer_v0.3.py t_clean.nwk -X 20 50 100 200 500` 

Just don't put the -X option before the positional argument

cheers

Fabrizio
