### ISSUE TITLE
Pruning to only keep a given set of sequences

### ISSUE THREAD

**Issue by fgaudilliere** [fmenardo/Treemmer#7]
Hi there, 

I'm currently trying to use Treemmer to reduce a very large tree of bacterial genomes and only keep a determined set of 4467 genomes. I used the following command to do this:

`python Treemmer/Treemmer_v0.3.py -lm metadata.csv -mc 4467 -X 4467 -r 200 bac120.tree`

The metadata file simply lists the IDs of the leaves I would like to keep, with each line looking something like: 
some_genome_ID, to keep

If I understood the pruning options correctly, this should tell Treemmer to trim the tree to 4467 leaves (-X 4467), and to keep at least 4467 leaves from each category listed in the metadata file (-lm metadata -mc 4467). Given that I only have one so-called 'category' in the metadata file ('to keep'), this should in theory lead to Treemmer outputing a tree with only the 4467 desired leaves. 

However, when I do this, while I do get 4467 leaves in the output tree, only about half of them are in my desired set of genomes. Could you tell me what I misunderstood in the pruning options? Is there maybe a much simpler way to get the tree I want? 

Best, 
Flora

EDIT: It seems that my problem lies with the tree I want to trim rather than with Treemmer itself. I'm still interested if there is a simpler way to get the tree I want though!

**Comment by fmenardo** [comment]
Hi @fgaudilliere,

Your usage is correct, that's the only way to do what you want to do with Treemmer,  probably the label names in the tree do not correspond to the ones in the list..

In any case, if you want a tree with a known subset of taxa, I would suggest to produce the tree from the alignment, if possible..

I hope this helps

Best  

Fabrizio

**Comment by fgaudilliere** [comment]
Thank you!
