### ISSUE TITLE
Incorporation as Dependency into Other Software Repositories

### ISSUE THREAD

**Issue by raufs** [fmenardo/Treemmer#8]
Hi,

Thank you for developing this amazing tool! I would like to include it as a dependency within some bioinformatic programs I am working on and was wondering if this would be ok to do? Specifically, I  would include your program in a sub-directory of the main repositories marked as `external_tools/` with licensing in-tact and have a notice to cite your paper if folks use it. 

Please let me know if there would be an issue with this or whether you have plans to add the program to PyPi or conda by chance?

Kind regards,
Rauf

**Comment by fmenardo** [comment]
Hi @raufs , sorry for the late answer. It's all fine by me, please go ahead. At the moment I have no plan to add it to conda or PyPi.
Best wishes
Fabrizio

**Comment by raufs** [comment]
Sounds great, thank you!
