### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by mdsufz** [fmenardo/Treemmer#9]
Hi Fernando,

The tool seems nice but there is no easy how-to in this tool. 

Is it possible for you to create a quick and easy to follow tutorial?

What are the inputs? Give an example of a command line using those inputs.

Right now it is unclear how to use this seemingly nice tool.

Best regards.

**Comment by fmenardo** [comment]
Hi @mdsufz 
I added a few examples withe basic usage to the README. Also please note that for more advanced pruning options there is a tutorial in examples/pruning_options_tutorial.
